data_dir: data/carp/weight_salinity/

batch_size: 32

max_epochs:   600
lr:           5.0e-4
weight_decay: 1.0e-4

pos_weight:           1.0
huber_delta:          50.0
loss_weight_presence: 0.0
loss_weight_length:   1.0

length_noise_std: 30.0

lr_patience:             30
early_stopping_patience: 100

checkpoint_dir: checkpoints/carp_weight_salinity_model/
